name: Compile examples foolder

on: [push, pull_request]

jobs:
 
 build-esp32:
    runs-on: ubuntu-latest
    #if: contains(github.event.head_commit.message, 'esp32')

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: esp32:esp32:esp32
          - fqbn: esp32:esp32:esp32c3
        core:
          - version: 3.0.6
          - version: 3.0.7
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Libraries
        run: |
              mkdir -p $HOME/Arduino/libraries
              cp -R lib/* $HOME/Arduino/libraries/
      
      - name: Compile ESP32 examples
        uses: arduino/compile-sketches@v1
        with:
          platforms: |
            - name: esp32:esp32
              source-url: https://espressif.github.io/arduino-esp32/package_esp32_index.json
              version: ${{ matrix.core.version }}
          fqbn: ${{ matrix.board.fqbn }}
          sketch-paths: |
            - ./
          libraries: |
            - name: AM2302-Sensor
            - name: DS3231-RTC
          cli-compile-flags: |
            - --library
            - "${{ github.workspace }}/include"
